version: 2

project_name: date-mcp

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: date-mcp
    binary: date-mcp
    dir: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Skip 32-bit builds and unsupported combinations
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: emj-io
    name: date-mcp
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## date-mcp {{ .Tag }}

    MCP (Model Context Protocol) server providing date/time functionality for AI applications.

    ### Installation

    Download the appropriate binary for your platform from the assets below.

    For Cursor IDE integration, add to `.cursor/mcp.json`:
    ```json
    {
      "mcpServers": {
        "date-mcp": {
          "command": "/path/to/date-mcp",
          "args": []
        }
      }
    }
    ```

  footer: |
    **Full Changelog**: https://github.com/emj-io/date-mcp/compare/{{ .PreviousTag }}...{{ .Tag }}

# Generate SBOM (Software Bill of Materials)
sboms:
  - artifacts: archive